const articles = [
  {
    title: '10 Best tech gadgets you need in your life',
    content:
      '<p>Your life is about to get a little simpler and more fulfilling with our list of the top 10 best gadgets for daily use. Because sometimes we need a helping hand or a nudge in the right direction to make healthier choices. If you’re reaching to tech for guidance, you’re in the right place with today’s Daily Digest. Enhance your leisure time, get more creative at work, feel safer indoors, and more with our list of the best tech gadgets for everyday use.&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><ul><li>We crafted a list of some must-have tech that you can easily incorporate into your daily routine. Want to stand up straighter? There’s a gadget for that. Planning on upping your fitness regime? We have the equipment for that. There’s so much more to discover in today’s article, too. Related:&nbsp;</li><li>&nbsp;</li><li>The best air purifiers of 2021 for your home We included a smart breath training system that assesses your breathing health and provides exercises to increase your lung capacity. We also included a smart robot vacuum that learns your cleaning habits and features voice assistants. Explore all of our recommended tech in the list below. 1. The Nintendo Switch OLED model features a vibrant 7-inch OLED screen and 64 GB of internal storage for fun gameplay.[text](link) 2. 3. 4. js ```console.log(\'test\');``` !<a href="test.com">[Rainbow@ordina.</a>png](</li></ul><p>&nbsp;</p><blockquote><p>/uploads/Rainbow_ordina_f934941d36.png) The Nintendo Switch OLED model provides three modes for play: TV, Handheld, and Tabletop. You can conveniently switch between these modes based on your needs.&nbsp;</p></blockquote><p>Best of all, the adjustable stand makes Tabletop mode ideal for multiplayer gaming. Or the built-in wired LAN port is great for using in the TV mode gaming. This item is available for order on October 8 for $349.99. 2. Take your well-being to new heights with the Airofit PRO smart breath training system. See improvements in your lung capacity in just a couple of weeks with 5–10 minutes of use daily. Designed in the form of a tiny gadget, you can take the Airofit PRO smart breath training system everywhere you go. It comes with an app that analyzes your lung capacity, anaerobic threshold, respiratory strength, and other areas of your breathing. You’ll then receive all of this data to your phone, where you can make improvements.</p>',
    original_date: '2021-07-23',
    slug: '10-best-tech-gadgets-you-need-in-your-life',
    description: 'A short article about anything',
    author: {
      id: 1,
      name: 'Menno Wielhouwer',
      email: 'menno.wielhouwer@ordina.nl',
      biography: null,
      published_at: '2021-07-05T14:28:17.809Z',
      created_at: '2021-07-05T14:28:16.571Z',
      updated_at: '2021-12-09T16:07:39.571Z',
      photo: {
        id: 1,
        name: '1517692035374.jpg',
        alternativeText: '',
        caption: '',
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            name: 'thumbnail_1517692035374.jpg',
            hash: 'thumbnail_1517692035374_b9f9834729',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 156,
            height: 156,
            size: 5.89,
            path: null,
            url: '/uploads/thumbnail_1517692035374_b9f9834729.jpg',
          },
        },
        hash: '1517692035374_b9f9834729',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 5.44,
        url: '/uploads/1517692035374_b9f9834729.jpg',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        created_at: '2021-07-05T14:27:30.413Z',
        updated_at: '2021-12-09T16:07:49.700Z',
      },
    },
    age: null,
    published_at: '2021-07-23T11:19:21.218Z',
    created_at: '2021-07-23T11:19:19.318Z',
    updated_at: '2021-12-09T16:07:39.559Z',
    cover_image: {
      id: 3,
      name: '0_rbOAXy4FebRclctb.jpeg',
      alternativeText: '',
      caption: '',
      width: 1024,
      height: 576,
      formats: {
        thumbnail: {
          name: 'thumbnail_0_rbOAXy4FebRclctb.jpeg',
          hash: 'thumbnail_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 245,
          height: 138,
          size: 5.34,
          path: null,
          url: '/uploads/thumbnail_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe.jpeg',
        },
        large: {
          name: 'large_0_rbOAXy4FebRclctb.jpeg',
          hash: 'large_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 1000,
          height: 563,
          size: 43.25,
          path: null,
          url: '/uploads/large_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe.jpeg',
        },
        medium: {
          name: 'medium_0_rbOAXy4FebRclctb.jpeg',
          hash: 'medium_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 750,
          height: 422,
          size: 28.06,
          path: null,
          url: '/uploads/medium_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe.jpeg',
        },
        small: {
          name: 'small_0_rbOAXy4FebRclctb.jpeg',
          hash: 'small_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 500,
          height: 281,
          size: 14.88,
          path: null,
          url: '/uploads/small_0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe.jpeg',
        },
      },
      hash: '0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe',
      ext: '.jpeg',
      mime: 'image/jpeg',
      size: 44.04,
      url: '/uploads/0_rb_OA_Xy4_Feb_Rclctb_5e31544bbe.jpeg',
      previewUrl: null,
      provider: 'local',
      provider_metadata: null,
      created_at: '2021-07-23T11:18:32.956Z',
      updated_at: '2021-07-23T11:18:32.965Z',
    },
    categories: [
      {
        id: 2,
        name: 'vue',
        slug: 'vue',
        published_at: '2021-08-05T11:52:16.185Z',
        created_at: '2021-07-28T14:18:25.122Z',
        updated_at: '2021-08-05T11:52:16.221Z',
      },
      {
        id: 1,
        name: 'angular',
        slug: 'angular',
        published_at: '2021-07-05T14:27:55.474Z',
        created_at: '2021-07-05T14:27:54.167Z',
        updated_at: '2021-07-05T14:27:55.489Z',
      },
    ],
  },
  {
    title: 'Apps I can’t live without (v2021)',
    content:
      '<p>With this post, my wish is to highlight some of the great apps I use in my daily life. Let me start by giving you some context that may help understand my choices a bit better. Personally, I’m a tech geek and an Apple fanboy, so I’ll be mostly talking about apps in the Apple ecosystem. Professionally I’ve been working in web development for the last 20 years, started as a developer, and now I lead tech and product teams. Currently, I’m CTO at sheerME. Let’s dive into the apps, starting with my Macbook Pro. I’m working in a 13-inch core i5 from 2016 with 16GB of ram (eagerly awaiting the arrival of my M1 Macbook Pro). The browser of choice: Google Chrome Two reasons why I prefer chrome, the devtools, and the extension ecosystem. These are the extensions I currently use: Metamask: A crypto wallet (I’m big into Ethereum)&nbsp;</p><p>&nbsp;</p><p>Defi Saver Gas Price extension: Also for the Ethereum ecosystem, it keeps me informed of gas prices (used to pay for transactions inside the network) Ghostery: My preferred ad blocker Raindrop.io: A very well done bookmark manager where I store bookmarks for future reference but also where I drop articles I want to read later. raindrop.io bookmark manager Mail Client: Superhuman It’s a bit on the expensive side but it helps me deal with email a lot faster than all the other clients I tried so for someone that spends a big chunk of his day on email, it’s well worth it. I’m very tempted to try hey.com from the basecamp guys but I can’t switch to a hey.com email address so for now I’ll stick with Superhuman. Calendar App: Fantastical Fantastical is all about the little details… the way you can identify a zoom, hangout, skype call or any other just by looking at the event in the calendar, the small icon that tells you how the weather is for the day, the natural language parser that enables you to create events just by typing what you want…&nbsp;</p><p>&nbsp;</p><blockquote><p>This is a quote</p></blockquote><p>&nbsp;</p><p>Fantastical Music Player: Spotif…Apple Music Being so entrenched in the Apple ecosystem it is very hard not to go with apple music, as much as I love Spotify, particularly the dynamic playlists that allow me to discover new music every day, Apple music just works so well across all my apple setup that I couldn’t resist. Note-taking: Roam Research As a very visual person I’m naturally drawn to apps like Bear notes or Craft but after a couple of tries, I’m now convinced that Rom is the best note-taking app for me. The main reason is that it solves my biggest problem with notes in general, the resurfacing of relevant content when needed. Before Roam, most of my notes would quickly fall by the wayside. With Roam, they just pop up when needed.</p>',
    original_date: '2021-08-20',
    slug: 'apps-i-can-t-live-without-v2021',
    description: 'The best apps to own right now',
    author: {
      id: 4,
      name: 'Barack Obama',
      email: 'barackobama@potus.com',
      biography: null,
      published_at: '2021-12-09T15:51:44.858Z',
      created_at: '2021-12-09T15:50:53.864Z',
      updated_at: '2021-12-09T15:51:44.875Z',
      photo: {
        id: 13,
        name: 'barack obama.jpg',
        alternativeText: '',
        caption: '',
        width: 1024,
        height: 576,
        formats: {
          thumbnail: {
            name: 'thumbnail_barack obama.jpg',
            hash: 'thumbnail_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 245,
            height: 138,
            size: 4.6,
            path: null,
            url: '/uploads/thumbnail_barack_obama_7e1ab2c7fe.jpg',
          },
          large: {
            name: 'large_barack obama.jpg',
            hash: 'large_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 1000,
            height: 563,
            size: 53.04,
            path: null,
            url: '/uploads/large_barack_obama_7e1ab2c7fe.jpg',
          },
          medium: {
            name: 'medium_barack obama.jpg',
            hash: 'medium_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 750,
            height: 422,
            size: 29.57,
            path: null,
            url: '/uploads/medium_barack_obama_7e1ab2c7fe.jpg',
          },
          small: {
            name: 'small_barack obama.jpg',
            hash: 'small_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 500,
            height: 281,
            size: 14.05,
            path: null,
            url: '/uploads/small_barack_obama_7e1ab2c7fe.jpg',
          },
        },
        hash: 'barack_obama_7e1ab2c7fe',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 56.62,
        url: '/uploads/barack_obama_7e1ab2c7fe.jpg',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        created_at: '2021-12-09T15:50:44.615Z',
        updated_at: '2021-12-09T15:50:44.624Z',
      },
    },
    age: null,
    published_at: '2021-07-23T11:25:23.421Z',
    created_at: '2021-07-23T11:22:59.181Z',
    updated_at: '2021-12-09T16:08:10.351Z',
    cover_image: {
      id: 4,
      name: '1_rhPxZdTRfNDlPa2rYdZKJw.jpeg',
      alternativeText: '',
      caption: '',
      width: 875,
      height: 428,
      formats: {
        thumbnail: {
          name: 'thumbnail_1_rhPxZdTRfNDlPa2rYdZKJw.jpeg',
          hash: 'thumbnail_1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 245,
          height: 120,
          size: 4.53,
          path: null,
          url: '/uploads/thumbnail_1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9.jpeg',
        },
        medium: {
          name: 'medium_1_rhPxZdTRfNDlPa2rYdZKJw.jpeg',
          hash: 'medium_1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 750,
          height: 367,
          size: 24.89,
          path: null,
          url: '/uploads/medium_1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9.jpeg',
        },
        small: {
          name: 'small_1_rhPxZdTRfNDlPa2rYdZKJw.jpeg',
          hash: 'small_1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9',
          ext: '.jpeg',
          mime: 'image/jpeg',
          width: 500,
          height: 245,
          size: 12.86,
          path: null,
          url: '/uploads/small_1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9.jpeg',
        },
      },
      hash: '1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9',
      ext: '.jpeg',
      mime: 'image/jpeg',
      size: 32.22,
      url: '/uploads/1_rh_Px_Zd_T_Rf_N_Dl_Pa2r_Yd_ZK_Jw_c3888126d9.jpeg',
      previewUrl: null,
      provider: 'local',
      provider_metadata: null,
      created_at: '2021-07-23T11:22:55.422Z',
      updated_at: '2021-12-09T16:47:01.658Z',
    },
    categories: [],
  },
  {
    id: 5,
    title: 'I Tested 3 Popular Side Hustles and Made Almost $3000',
    content:
      '<p>Selling friendship bracelets on Etsy is not my cup of tea. I don’t want to spend my limited time on this earth on proposed side hustles you commonly find out there unless there is a relatively large payoff. I have encountered and read about hundreds of ways to earn an extra buck thanks to good ‘ol Google. However, I found that a lot of them needed either: Some sort of upfront financial investment An unrealistic time commitment for little payback Whether you are saving for an investment, a vacation, or just some extra spending money, having a side hustle can be a game-changer. I thought, why not choose 3 side hustles and put them to the test! I gave each one 30 days in order to give them something to measure up to and to my utter surprise, they each earned in the $1000 ballpark! Without further ado, here are three side hustles tested out by yours truly, listed from most profitable to least profitable. Upselling Ikea Items From the ‘As Is’ Section This is by far my favorite of the three side hustles. I would actually describe this as more of a life hack than a side hustle and can see myself doing it …forever. I discovered the idea through a YouTube channel called “Our Rich Journey”. The couple who run the channel chased the FIRE movement (financial independence, retire early) and managed to retire before the age of 40 thanks to their incredible execution of stock market investing, real estate investing, and side hustles. If you’re going to base your side hustle game off of anyone, this is the couple to do it with. Essentially, you visit your local Ikea, go to the ‘as is’ section and search for largely discounted, minimally damaged items. Once purchased, post and sell them on private platforms such as Facebook Marketplace, Kijiji, or Craigslist — dealers choice. Over two trips I purchased: 3 identical bathroom vanities that cost $60 in total (they were heavily discounted at 70% off with no apparent damages. Full price would have been over $600) 1 kitchen table for $80 (this was also significantly discounted at 90% off, so it would have cost just north of $700 had it not been in the as-is section. The only damage was a small white paint stain that I scraped off). A very important side note — because you are paying a small upfront cost, be sure to take a few minutes before you make your purchase to pull out your phone and do some research. For example, if you plan on selling on Facebook Marketplace, take a quick look and see what comparable items are selling for so that you will not only make your money back, but you will also walk away with a healthy profit. The drive home from my second trip was a bit of a low point. I was losing the high I had gotten from shopping and finding such good deals. I was quickly realizing that I was in the hole $140 and was questioning whether I was losing my mind in this quest for quick money.</p>',
    original_date: '2021-07-24',
    slug: 'i-tested-3-popular-side-hustles-and-made-almost-3000',
    description:
      'Joran, read more from Juliet Collados — and everyone else on Medium.\nYou’ve read all your free member-only stories. Become a member to get unlimited access and support the voices you want to hear more from.\nUpgrade',
    author: {
      id: 1,
      name: 'Menno Wielhouwer',
      email: 'menno.wielhouwer@ordina.nl',
      biography: null,
      published_at: '2021-07-05T14:28:17.809Z',
      created_at: '2021-07-05T14:28:16.571Z',
      updated_at: '2021-12-09T16:07:39.571Z',
      photo: {
        id: 1,
        name: '1517692035374.jpg',
        alternativeText: '',
        caption: '',
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            name: 'thumbnail_1517692035374.jpg',
            hash: 'thumbnail_1517692035374_b9f9834729',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 156,
            height: 156,
            size: 5.89,
            path: null,
            url: '/uploads/thumbnail_1517692035374_b9f9834729.jpg',
          },
        },
        hash: '1517692035374_b9f9834729',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 5.44,
        url: '/uploads/1517692035374_b9f9834729.jpg',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        created_at: '2021-07-05T14:27:30.413Z',
        updated_at: '2021-12-09T16:07:49.700Z',
      },
    },
    age: null,
    published_at: '2021-07-23T11:25:19.234Z',
    created_at: '2021-07-23T11:25:16.684Z',
    updated_at: '2021-12-09T16:08:23.772Z',
    cover_image: {
      id: 5,
      name: '0_U70r_PVfcpewdD3f.jpg',
      alternativeText: '',
      caption: '',
      width: 1250,
      height: 833,
      formats: {
        thumbnail: {
          name: 'thumbnail_0_U70r_PVfcpewdD3f.jpg',
          hash: 'thumbnail_0_U70r_P_Vfcpewd_D3f_d64782dc14',
          ext: '.jpg',
          mime: 'image/jpeg',
          width: 234,
          height: 156,
          size: 8.06,
          path: null,
          url: '/uploads/thumbnail_0_U70r_P_Vfcpewd_D3f_d64782dc14.jpg',
        },
        large: {
          name: 'large_0_U70r_PVfcpewdD3f.jpg',
          hash: 'large_0_U70r_P_Vfcpewd_D3f_d64782dc14',
          ext: '.jpg',
          mime: 'image/jpeg',
          width: 1000,
          height: 666,
          size: 78.88,
          path: null,
          url: '/uploads/large_0_U70r_P_Vfcpewd_D3f_d64782dc14.jpg',
        },
        medium: {
          name: 'medium_0_U70r_PVfcpewdD3f.jpg',
          hash: 'medium_0_U70r_P_Vfcpewd_D3f_d64782dc14',
          ext: '.jpg',
          mime: 'image/jpeg',
          width: 750,
          height: 500,
          size: 48.61,
          path: null,
          url: '/uploads/medium_0_U70r_P_Vfcpewd_D3f_d64782dc14.jpg',
        },
        small: {
          name: 'small_0_U70r_PVfcpewdD3f.jpg',
          hash: 'small_0_U70r_P_Vfcpewd_D3f_d64782dc14',
          ext: '.jpg',
          mime: 'image/jpeg',
          width: 500,
          height: 333,
          size: 25.33,
          path: null,
          url: '/uploads/small_0_U70r_P_Vfcpewd_D3f_d64782dc14.jpg',
        },
      },
      hash: '0_U70r_P_Vfcpewd_D3f_d64782dc14',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 120.1,
      url: '/uploads/0_U70r_P_Vfcpewd_D3f_d64782dc14.jpg',
      previewUrl: null,
      provider: 'local',
      provider_metadata: null,
      created_at: '2021-07-23T11:24:42.729Z',
      updated_at: '2021-07-23T11:24:42.740Z',
    },
    categories: [
      {
        id: 2,
        name: 'vue',
        slug: 'vue',
        published_at: '2021-08-05T11:52:16.185Z',
        created_at: '2021-07-28T14:18:25.122Z',
        updated_at: '2021-08-05T11:52:16.221Z',
      },
    ],
  },
  {
    id: 6,
    title: 'Async Nature of JavaScript',
    content:
      '<p>If you are new to JavaScript then you must have heard that JavaScript is an asynchronous language but what if I say you are wrong JavaScript is not asynchronous it is a synchronous language, then why is everyone saying it is Async. Let’s read the below article to understand. What is Synchronous JavaScript? When you write a piece of code and each code of line executes one after another, then it is a synchronous. Each step of operation waits for the previous step to execute completely. Let’s see an example below to understand this. Fig 1. A synchronous function to calculate the sum of two number In the Fig 1, let’s see how the code works. The code is executed as below: The first line of code which will execute is getSum=add(2,3). This will call the function add in the first line. Then the sum of a and b is stored in constant variable sum. Then this sum is returned and it stores the value in const variable getSum Then the getSum is printed at last. In the above we can observe that console.log is waiting for the sum to be returned. This is because JavaScript is a single threaded, only one thing can happen at single point of time in the single thread, hence it is waiting for the previous step to execute until then everything is blocked. What is Asynchronous JavaScript? When you write a piece of code and a particular step doesn’t wait for the previous step to execute completely, then it is asynchronous. This happens when a API is called which uses external device to get the data, then it doesn’t make sense to block the entire execution until the data comes and then to execute the next steps. Let’s see an example below to understand.&nbsp;</p><p>&nbsp;</p><p>Fig 2. An asynchronous function setTimeout which prints the sum after 3s. In the Fig 2, what do you think will be the output of the above code? Will the ‘The sum of 2 and 3 is 5’ print first followed by value of sum or will it print later. Let’s see how the code works, the code is executed as below: The first line of code which will execute is getSum=add(2,3). This will call the function add in the first line. Then the sum of a and b is stored in constant variable sum. Now the setTimeout doesn’t run immediately, it is sent to the browser to execute that, once it is executed the callback function is sent to event queue(will discuss about this later). Then this sum is returned and it stores the value in const variable getSum Then the getSum is printed at last. Now when the call stack gets empty then the callback function comes to the main thread and will print ‘The sum of 2 and 3 is 5’ after 3s So what happened above, why ‘The sum of 2 and 3 is 5’ printed after ‘5’ even when it was called before. It is because we have a concept of event queue and event loop which executes the async calls only after the call stack is empty. What is Event Queue and Event Loop? Async calls are put into event queue or callback queue, which runs after the call stack becomes empty i.e after the main thread has finished processing all the operations, so that these async calls do not block the next javascript codes from running. Fig 3. How Event loop and Callback Queue works in JS Engine In the Fig 3, these callback queues are sent back to the main thread once all the codes are executed inside it and then these queued codes are executed. The event queues are sent back to the main thread with the help of event loop. The event loop continuously runs and check if the main thread has become empty or not, as soon as the main thread becomes empty the queues are pushed to the call stack. Conclusion As we read above, it proves JS is a synchronous, blocking and single threaded language. It is the external API’s which make the language behave asynchronous and to overcome these there is a concept of event queue and event loop. These things are controlled by JavaScript engine and not the Javascript itself. The browsers have the engine, V8 is one of the most used engine.</p>',
    original_date: '2021-07-30',
    slug: 'async-nature-of-java-script',
    description: 'sdf',
    author: {
      id: 1,
      name: 'Menno Wielhouwer',
      email: 'menno.wielhouwer@ordina.nl',
      biography: null,
      published_at: '2021-07-05T14:28:17.809Z',
      created_at: '2021-07-05T14:28:16.571Z',
      updated_at: '2021-12-09T16:07:39.571Z',
      photo: {
        id: 1,
        name: '1517692035374.jpg',
        alternativeText: '',
        caption: '',
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            name: 'thumbnail_1517692035374.jpg',
            hash: 'thumbnail_1517692035374_b9f9834729',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 156,
            height: 156,
            size: 5.89,
            path: null,
            url: '/uploads/thumbnail_1517692035374_b9f9834729.jpg',
          },
        },
        hash: '1517692035374_b9f9834729',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 5.44,
        url: '/uploads/1517692035374_b9f9834729.jpg',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        created_at: '2021-07-05T14:27:30.413Z',
        updated_at: '2021-12-09T16:07:49.700Z',
      },
    },
    age: null,
    published_at: '2021-07-23T11:26:41.803Z',
    created_at: '2021-07-23T11:26:39.475Z',
    updated_at: '2021-12-09T16:15:41.956Z',
    cover_image: {
      id: 6,
      name: '1_y79dXEpDG4pJiNBOST1t4A.png',
      alternativeText: '',
      caption: '',
      width: 652,
      height: 225,
      formats: {
        thumbnail: {
          name: 'thumbnail_1_y79dXEpDG4pJiNBOST1t4A.png',
          hash: 'thumbnail_1_y79d_X_Ep_DG_4p_Ji_NBOST_1t4_A_7dcfe79a6e',
          ext: '.png',
          mime: 'image/png',
          width: 245,
          height: 85,
          size: 10.79,
          path: null,
          url: '/uploads/thumbnail_1_y79d_X_Ep_DG_4p_Ji_NBOST_1t4_A_7dcfe79a6e.png',
        },
        small: {
          name: 'small_1_y79dXEpDG4pJiNBOST1t4A.png',
          hash: 'small_1_y79d_X_Ep_DG_4p_Ji_NBOST_1t4_A_7dcfe79a6e',
          ext: '.png',
          mime: 'image/png',
          width: 500,
          height: 173,
          size: 30.95,
          path: null,
          url: '/uploads/small_1_y79d_X_Ep_DG_4p_Ji_NBOST_1t4_A_7dcfe79a6e.png',
        },
      },
      hash: '1_y79d_X_Ep_DG_4p_Ji_NBOST_1t4_A_7dcfe79a6e',
      ext: '.png',
      mime: 'image/png',
      size: 9.77,
      url: '/uploads/1_y79d_X_Ep_DG_4p_Ji_NBOST_1t4_A_7dcfe79a6e.png',
      previewUrl: null,
      provider: 'local',
      provider_metadata: null,
      created_at: '2021-07-23T11:26:31.939Z',
      updated_at: '2021-07-23T11:26:31.951Z',
    },
    categories: [
      {
        id: 5,
        name: 'mendix',
        slug: 'mendix',
        published_at: '2021-12-09T15:47:42.661Z',
        created_at: '2021-12-09T15:47:29.545Z',
        updated_at: '2021-12-09T15:48:20.876Z',
      },
      {
        id: 1,
        name: 'angular',
        slug: 'angular',
        published_at: '2021-07-05T14:27:55.474Z',
        created_at: '2021-07-05T14:27:54.167Z',
        updated_at: '2021-07-05T14:27:55.489Z',
      },
    ],
  },
  {
    id: 15,
    title: 'The arrival of Java 17!',
    content:
      '<p>Oracle is proud to announce the general availabilty of JDK 17. This release is the eighth Feature Release delivered on time through the six-month release cadence. This level of predictability allows developers to easily manage their adoption of innovation thanks to s steady stream of expected changes.</p><p>&nbsp;</p><p>Java’s ability to boost performance, stability, and security continues to make it the world’s most popular programming language. According to an IDC report over ten&nbsp;million developers, representing 75% of full-time developers worldwide, use Java, more than any other language.</p><p>&nbsp;</p><p><strong>JDK 17 is now available!</strong></p><p><a href="https://www.oracle.com/news/announcement/oracle-releases-java-17-2021-09-14/">Oracle now offers JDK 17 for developers, end-users, and enterprises.&nbsp;</a>As an LTS release, Oracle JDK 17 will receive performance, stability and security updates for at least 8 years following the <a href="https://www.oracle.com/technetwork/topics/security/alerts-086861.html">Oracle Critical Patch Update (CPU) schedule</a> as outlined in <a href="https://www.oracle.com/java/technologies/java-se-support-roadmap.html">the Oracle Java SE Support Roadmap</a>.</p><p>Oracle JDK 18, the next six month cadence release is now scheduled for in March 2022.</p><p>Java 17 is the second long-term support (LTS) under the release cadence announced in 2018. <a href="https://blogs.oracle.com/java/post/moving-the-jdk-to-a-two-year-lts-cadence">Oracle has announced plans to shorten the time between future LTS releases</a>, from 3 years to 2 years so you should expect the next LTS to be Java 21 in September of 2023.</p><p>Another important change with Oracle JDK 17 is <a href="https://blogs.oracle.com/java/post/free-java-license">new simple license terms</a> which will allow companies to use Oracle JDK 17, including the quarterly performance, stability, and security patches, at no cost for at least the next three years, allowing one full year of overlap with the next LTS release. Java SE Subscribers get access to Oracle’s Java SE Support and commercial features such as GraalVM Enterprise, Java Management Service and the Advanced Management Console.</p><p><strong>Java 17, Together</strong></p><p>As with previous release, with Java 17, we continue to celebrate the contributions from many individuals and organizations in the OpenJDK Community — we all build Java, together!</p><p><strong>JDK 17 Fix Ratio</strong></p><p>The rate of change over time in the JDK releases has remained largely constant for years, but under the six-month cadence the pace at which production-ready features and improvements are delivered has vastly improved.</p><p>Instead of making tens of thousands of fixes and delivering close to one hundred JEPs (JDK Enhancement Proposals) every few years as we did with yesteryear Major Releases, enhancements are delivered in leaner Feature Releases on a more manageable, predictable six-month schedule. The changes range from significant new features to small enhancements to routine maintenance, bug fixes, and documentation improvements. Each change is represented in a single commit for a single issue in the <a href="https://bugs.openjdk.java.net/secure/Dashboard.jspa">JDK Bug System</a>.</p><p>Of the 12,733 JIRA issues marked as fixed in Java 12 through Java 17 at the time of their GA, 9,218 were completed by people working for Oracle while 3,515 were contributed by individual developers and developers working for other organizations.</p><p>In Java 17, of the 2,645 JIRA issues marked as fixed, 1,774 were completed by Oracle, while 871 were contributed by other members of the Java community. Going through the issues and collating the organization data from assignees results in the following chart of organizations sponsoring the development of contributions in Java 17:</p><p>&nbsp;</p><p>Oracle would like to thank the developers working for organizations like Amazon, NTT Data, Red Hat, SAP and Tencent for their notable contributions.&nbsp; We are also thankful to see contributions from smaller organizations such as Bellsoft, DataDog, Loongson, Skymatic and independent developers who collectively contributed 6% of the fixes in Java 17.</p><p>We are equally grateful to the many experienced developers who reviewed proposed changes, the early adopters who tried out early access builds and reported issues, and the dedicated professionals who provided feedback on the OpenJDK mailing lists.&nbsp;</p>',
    original_date: '2021-09-14',
    slug: 'the-arrival-of-java-17',
    description: 'The all new Java',
    author: {
      id: 4,
      name: 'Barack Obama',
      email: 'barackobama@potus.com',
      biography: null,
      published_at: '2021-12-09T15:51:44.858Z',
      created_at: '2021-12-09T15:50:53.864Z',
      updated_at: '2021-12-09T15:51:44.875Z',
      photo: {
        id: 13,
        name: 'barack obama.jpg',
        alternativeText: '',
        caption: '',
        width: 1024,
        height: 576,
        formats: {
          thumbnail: {
            name: 'thumbnail_barack obama.jpg',
            hash: 'thumbnail_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 245,
            height: 138,
            size: 4.6,
            path: null,
            url: '/uploads/thumbnail_barack_obama_7e1ab2c7fe.jpg',
          },
          large: {
            name: 'large_barack obama.jpg',
            hash: 'large_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 1000,
            height: 563,
            size: 53.04,
            path: null,
            url: '/uploads/large_barack_obama_7e1ab2c7fe.jpg',
          },
          medium: {
            name: 'medium_barack obama.jpg',
            hash: 'medium_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 750,
            height: 422,
            size: 29.57,
            path: null,
            url: '/uploads/medium_barack_obama_7e1ab2c7fe.jpg',
          },
          small: {
            name: 'small_barack obama.jpg',
            hash: 'small_barack_obama_7e1ab2c7fe',
            ext: '.jpg',
            mime: 'image/jpeg',
            width: 500,
            height: 281,
            size: 14.05,
            path: null,
            url: '/uploads/small_barack_obama_7e1ab2c7fe.jpg',
          },
        },
        hash: 'barack_obama_7e1ab2c7fe',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 56.62,
        url: '/uploads/barack_obama_7e1ab2c7fe.jpg',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        created_at: '2021-12-09T15:50:44.615Z',
        updated_at: '2021-12-09T15:50:44.624Z',
      },
    },
    age: null,
    published_at: '2021-12-09T16:10:41.543Z',
    created_at: '2021-12-09T16:10:37.999Z',
    updated_at: '2021-12-09T17:04:22.830Z',
    cover_image: {
      id: 14,
      name: 'download.png',
      alternativeText: '',
      caption: '',
      width: 2145,
      height: 1145,
      formats: {
        thumbnail: {
          name: 'thumbnail_download.png',
          hash: 'thumbnail_download_7a99e86084',
          ext: '.png',
          mime: 'image/png',
          width: 245,
          height: 131,
          size: 11,
          path: null,
          url: '/uploads/thumbnail_download_7a99e86084.png',
        },
        large: {
          name: 'large_download.png',
          hash: 'large_download_7a99e86084',
          ext: '.png',
          mime: 'image/png',
          width: 1000,
          height: 534,
          size: 63.99,
          path: null,
          url: '/uploads/large_download_7a99e86084.png',
        },
        medium: {
          name: 'medium_download.png',
          hash: 'medium_download_7a99e86084',
          ext: '.png',
          mime: 'image/png',
          width: 750,
          height: 400,
          size: 44,
          path: null,
          url: '/uploads/medium_download_7a99e86084.png',
        },
        small: {
          name: 'small_download.png',
          hash: 'small_download_7a99e86084',
          ext: '.png',
          mime: 'image/png',
          width: 500,
          height: 267,
          size: 26.72,
          path: null,
          url: '/uploads/small_download_7a99e86084.png',
        },
      },
      hash: 'download_7a99e86084',
      ext: '.png',
      mime: 'image/png',
      size: 157.87,
      url: '/uploads/download_7a99e86084.png',
      previewUrl: null,
      provider: 'local',
      provider_metadata: null,
      created_at: '2021-12-09T16:10:23.897Z',
      updated_at: '2021-12-09T16:10:23.907Z',
    },
    categories: [
      {
        id: 6,
        name: 'java',
        slug: 'java',
        published_at: '2021-12-09T15:48:11.721Z',
        created_at: '2021-12-09T15:48:10.057Z',
        updated_at: '2021-12-09T15:48:26.640Z',
      },
    ],
  },
]

export default articles
